# permissions for end users to view secs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sec-viewer-role
rules:
- apiGroups:
  - ralap.io.sec
  resources:
  - secs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ralap.io.sec
  resources:
  - secs/status
  verbs:
  - get
