# permissions for end users to edit secs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sec-editor-role
rules:
- apiGroups:
  - ralap.io.sec
  resources:
  - secs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ralap.io.sec
  resources:
  - secs/status
  verbs:
  - get
